# Generated by Django 5.1.15 on 2026-02-15 21:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('url', models.URLField(max_length=2048)),
                ('mode', models.CharField(choices=[('quick', 'quick'), ('detailed', 'detailed')], default='quick', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('discovering', 'discovering'), ('extracting', 'extracting'), ('enhancing', 'enhancing'), ('generating', 'generating'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('result_llms_txt', models.TextField(blank=True)),
                ('result_meta', models.JSONField(blank=True, null=True)),
                ('llms_full_txt_key', models.CharField(blank=True, max_length=512)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='jobs_job_user_id_58dc09_idx'), models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'), models.Index(fields=['url', 'mode', '-created_at'], name='jobs_job_url_76c602_idx')],
            },
        ),
    ]
